export enum FINANCE_STATUSES {
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  APPROVED_BY = 'SYSTEM',
  }

export const FINANCE_APPLICATION_STATUS = {
  PENDING: 'PENDING',
  REJECTED: 'REJECTED',
  PARTIALLY_APPROVED: 'PARTIALLY_APPROVED',
  APPROVED: 'APPROVED'
}

export const FINANCE_APPLICATION_PROCESSING_STATUS = {
  PENDING: 'PENDING',
  REJECTED_BY_SYSTEM: 'REJECTED_BY_SYSTEM',
  REJECTED_BY_AGENT: 'REJECTED_BY_AGENT',
  WAITING_FOR_APPROVAL: 'WAITING_FOR_APPROVAL',
  PARTIALLY_APPROVED: 'PARTIALLY_APPROVED',
  REJECTED: 'REJECTED',
  APPROVED: 'APPROVED'
}