export const TABLE = {
  USER: 'ENT_USER',
  MDS_TENANT: 'MDS_TENANT',
  MDS_APP_VERSION: 'MDS_APP_VERSION',
  MDS_CHANNEL: 'MDS_CHANNEL',
  MDS_ASSET_TYPE: 'MDS_ASSET_TYPE',
  MDS_ASSET: 'MDS_ASSET',
  AUDIT_LOG: 'AUD_AUDIT_LOG',
  // Finance.Service
  FN_APPLICATION:"FN_APPLICATION",
  FN_APPLICATION_APPROVALS:"FN_APPLICATION_APPROVALS",
  FN_INSTALLMENT_PLAN:"FN_INSTALLMENT_PLAN",
  FN_PAYMENT:"FN_PAYMENT",
  FN_APPLICATION_STATUS_VIEW:"FN_APPLICATION_STATUS_VIEW",
  // Notification.service
  NOTIFICATION: 'NFT_NOTIFICATION',
  NOTIFICATION_TEMPLATE: 'NFT_TEMPLATE',
  IN_APP_NOTIFICATION:'IN_APP_NOTIFICATION',
  // Customer.service
  CUSTOMER: 'CUS_CUSTOMER',
  COMPANY: 'CUS_COMPANY',
  AUTH_FLOW: 'CUS_AUTH_FLOW',
  FACTOR: 'CUS_FACTOR',
  AUTH_FLOW_FACTOR: 'CUS_AUTH_FLOW_FACTOR',
  DEVICE: 'CUS_DEVICE',
  SESSION: 'CUS_SESSION',
  MDS_REFERENCE: 'MDS_REFERENCE',
  MDS_CAMPAIGN: 'MDS_CAMPAIGN',
  WF_REQUEST: 'WF_REQUEST',
  OTP_SECRET: 'NFT_OTP_SECRET',
  OTP_VERIFICATION: 'NFT_OTP_VERIFICATION',
  MDS_TRANSLATION:'MDS_TRANSLATION',
  UI_PAGE: 'UI_PAGE',
  // Admin Service
  ADM_ADMIN_USER:'ADM_ADMIN_USER'
};

